controller_list:
  - name: ""
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory 
    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]

  - name: ""
    action_ns: sim1/joint_trajectory_action
    type: FollowJointTrajectory
    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
  
  - name: ""
    action_ns: sim2/joint_trajectory_action
    type: FollowJointTrajectory 
    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
    
  - name: ""
    action_ns: real/joint_trajectory_action
    type: FollowJointTrajectory 
    joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
